# Type stubs for rbatis_py._core (PyO3 native module)
# This file provides type hints for IDE autocompletion.

from typing import Any, Dict, List, Optional


class RBatis:
    """High-performance async database client."""

    def __init__(self) -> None: ...

    # --- Connection ---
    async def link(self, url: str) -> None: ...
    async def link_sqlite(self, url: str) -> None: ...
    async def link_mysql(self, url: str) -> None: ...
    async def link_postgres(self, url: str) -> None: ...
    async def link_mssql(self, url: str) -> None: ...
    async def link_turso(self, url: str) -> None: ...
    async def link_duckdb(self, url: str) -> None: ...

    def is_connected(self) -> bool: ...
    async def ping(self) -> bool: ...
    def close(self) -> None: ...

    # --- Pool Configuration ---
    async def set_pool_max_size(self, max_size: int) -> None: ...
    async def set_pool_max_idle(self, max_idle: int) -> None: ...
    async def set_pool_connect_timeout(self, timeout_secs: int) -> None: ...
    async def set_pool_max_lifetime(self, lifetime_secs: int) -> None: ...
    async def pool_state(self) -> Dict[str, Any]: ...

    # --- Connection / Transaction ---
    async def acquire(self) -> "Connection": ...
    async def begin(self) -> "Transaction": ...
    def begin_defer(self) -> "AutoCommitGuard": ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...

    # --- SQL Execution ---
    async def exec(self, sql: str, params: Optional[List[Any]] = None) -> int: ...
    async def exec_decode(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> List[Dict[str, Any]]: ...

    # --- CRUD ---
    async def insert(self, table: str, data: Dict[str, Any]) -> int: ...
    async def insert_batch(self, table: str, data_list: List[Dict[str, Any]], batch_size: Optional[int] = None) -> int: ...
    async def select_by_map(
        self, table: str, condition: Dict[str, Any]
    ) -> List[Dict[str, Any]]: ...
    async def update_by_map(
        self, table: str, data: Dict[str, Any], condition: Dict[str, Any]
    ) -> int: ...
    async def delete_by_map(self, table: str, condition: Dict[str, Any]) -> int: ...


class Transaction:
    """Explicit transaction. Requires manual commit() or rollback()."""

    async def exec(self, sql: str, params: Optional[List[Any]] = None) -> int: ...
    async def exec_decode(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> List[Dict[str, Any]]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    def auto_commit(self) -> "AutoCommitGuard": ...


class AutoCommitGuard:
    """Async context manager with SQL execution.
    Auto-commits on success, auto-rollbacks on exception.

    Usage:
        tx = await db.begin()
        async with tx.auto_commit() as g:
            await g.exec("INSERT ...")
    """

    async def __aenter__(self) -> "AutoCommitGuard": ...
    async def __aexit__(
        self,
        exc_type: Optional[type],
        exc_val: Optional[BaseException],
        exc_tb: Optional[object],
    ) -> Optional[bool]: ...

    async def exec(self, sql: str, params: Optional[List[Any]] = None) -> int: ...
    async def exec_decode(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> List[Dict[str, Any]]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class Connection:
    """A raw connection acquired from the pool."""

    async def exec(self, sql: str, params: Optional[List[Any]] = None) -> int: ...
    async def exec_decode(
        self, sql: str, params: Optional[List[Any]] = None
    ) -> List[Dict[str, Any]]: ...
    async def begin(self) -> Transaction: ...
    def close(self) -> None: ...
